serial_port_test_node:
  ros__parameters:
    serial_port_name: /dev/robot_base
    serial_baud_rate: 230400
    imu_frame: imu_link
    imu_topic: /imu/data
    odom_frame: odom
    odom_topic: /odom
    base_frame: base_link
    battery_voltage_topic: /battery/voltage
    velocity_cmd2ctr_topic: /cmd_vel
    beep_topic: /beep
